before_install:
  - wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp
  - sudo mkdir /usr/local/include/catch2
  - sudo mv catch.hpp /usr/local/include/catch2
language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - make test
dist: bionic
addons:
  apt:
    packages:
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libgmp-dev
